ALTER TABLE usuarios
    ADD COLUMN nombre VARCHAR(50) NOT NULL;

ALTER TABLE usuarios
    ADD COLUMN apellidos VARCHAR(50) NOT NULL;

ALTER TABLE usuarios
    ADD CONSTRAINT "USUARIO_EMAIL_UNIQUE" UNIQUE (email);

