version: '3.1'

services:
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gaming_platform
    ports:
      - 5432:5432