spring:
  profiles:
    active: prod
---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOSTNAME:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB_NAME:gaming}
    username: ${POSTGRESQL_DB_USER:gamer}
    password: ${POSTGRESQL_DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

cron:
  mail:
    batallas: 0 */1 * * * *

mail:
  host: smtp.gmail.com
  port: 587
  user: juceruta3x@gmail.com
  password: ptkjhwpeupkfwodi
  from: juceruta3x@gmail.com


