spring:
  profiles:
    active: prod
---
logging:
  level:
    com.mozcalti.gamingapp: DEBUG

security:
  account:
    activation:
      token-validity: 3 #3 dias
  jwt:
    token:
      secret: 4K2qXPg@14lCwV360#XCGt&#B3#?s!p0
      duration: 36000
      prefix: Bearer
  paths:
    open-paths: /, /static/**, /index.html, /css/**, /js/**, /img/**, /api/login/**, /users/verifyToken/**, /users/registrationConfirm/**

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOSTNAME:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB_NAME:gaming}
    username: ${POSTGRESQL_DB_USER:user}
    password: ${POSTGRESQL_DB_PASSWORD:pass}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: off

resources:
  static:
    instituciones: ${PATH_INSTITUCIONES:path}
    participantes: ${PATH_PARTICIPANTES:path}
    resultados-batalla: ${PATH_RESULTADOS_BATALLA:path}

robocode:
  executable: ${PATH_ROBOCODE:path}
  robots: ${PATH_ROBOTS:path}
  battles: ${PATH_BATTLES:path}

server:
  error:
    whitelabel:
      enabled: false

cron:
  mail-batallas: ${CRON_MAIL_BATTALLAS:0 */5 * * * *}
  resultados-batallas: ${CRON_RESULTADOS_BATTALLAS:0 */1 * * * *}

mail:
  host: ${MAIL_HOST:host}
  port: ${MAIL_PORT:port}
  user: ${MAIL_USER:user}
  password: ${MAIL_PASSWORD:password}
  from: ${MAIL_FROM:from}
  

