spring:
  profiles:
    active: prod
---
logging:
  level:
    com.mozcalti.gamingapp: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:path}
    name: ${LOGGING_FILE_NAME:name}

security:
  account:
    activation:
      token-validity: 3 #3 dias
  jwt:
    token:
      secret: 4K2qXPg@14lCwV360#XCGt&#B3#?s!p0
      duration: 36000
      prefix: Bearer
  paths:
    open-paths: /, /static/**, /index.html, /css/**, /js/**, /img/**, /api/login/**, /users/verifyToken/**, /users/registrationConfirm/**, /battle/**, /visualizar/**

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOSTNAME:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB_NAME:gaming}
    username: ${POSTGRESQL_DB_USER:user}
    password: ${POSTGRESQL_DB_PASSWORD:pass}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: off

resources:
  static:
    instituciones: ${PATH_INSTITUCIONES:path}
    participantes: ${PATH_PARTICIPANTES:path}

robocode:
  executable: ${PATH_ROBOCODE:path}
  robots: ${PATH_ROBOTS:path}
  battles: ${PATH_BATTLES:path}

server:
  port: ${SERVER_PORT:443}
  baseUrl: ${BASE_URL:https://robocode.mozcalti.com}
  ssl:
    key-store-password: ${KEY_STORE_PASSWORD:pass}
    keyStoreType: ${KEY_STORE_TYPE:type}
    keyAlias: ${KEY_ALIAS:tomcat}
    key-store: ${KEY_STORE:path}
    enabled: true
  error:
    whitelabel:
      enabled: false

cron:
  ejecuta-batallas: ${CRON_EJECUTA_BATTALLAS:0 */1 * * * *}

mail:
  host: ${MAIL_HOST:host}
  port: ${MAIL_PORT:port}
  user: ${MAIL_USER:user}
  password: ${MAIL_PASSWORD:password}
  from: ${MAIL_FROM:from}

view:
  htmlViewBattle: ${HTML_VIEW_BATTLE:html}
  xmlViewBattle: ${PATH_XML_VIEW:path}
  jsonViewBattle: ${PATH_JSON_VIEW:path}
