spring:
  profiles:
    active: prod
---
logging:
  level:
    com.mozcalti.gamingapp: DEBUG

security:
  account:
    activation:
      token-validity: 3 #3 dias
  jwt:
    token:
      duration: 36000
      prefix: Bearer
  paths:
    open-paths: /, /index.html, /css/**, /js/**, /img/**, /api/login/**, /users/verifyToken/**, /users/registrationConfirm/**

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOSTNAME:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB_NAME:gaming}
    username: ${POSTGRESQL_DB_USER:user}
    password: ${POSTGRESQL_DB_PASSWORD:pass}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: off

resources:
  static:
    instituciones: ${PATH_INSTITUCIONES:C:/tmp/robocode/instituciones}
    participantes: ${PATH_PARTICIPANTES:C:/tmp/robocode/participantes}
    resultados-batalla: ${PATH_RESULTADOS_BATALLA:C:/tmp/robocode/resultados}

server:
  error:
    whitelabel:
      enabled: false

cron:
  mail-batallas: ${CRON_MAIL_BATTALLAS:0 */5 * * * *}
  resultados-batallas: ${CRON_RESULTADOS_BATTALLAS:0 */1 * * * *}

mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  user: ${MAIL_USER:juceruta3x@gmail.com}
  password: ${MAIL_PASSWORD:ptkjhwpeupkfwodi}
  from: ${MAIL_FROM:juceruta3x@gmail.com}
  

